version: '3.3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfiles/bot/Dockerfile
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfiles/api/Dockerfile
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "8008:8008"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  static_value:
  media_value:
